{'url': 'http://stackoverflow.com/questions/129507/how-do-you-test-that-a-python-function-throws-an-exception', 'status': 200, 'method': 'GET', 'timestamp': 1467304217.39995, 'response_url': 'http://stackoverflow.com/questions/129507/how-do-you-test-that-a-python-function-throws-an-exception'}